components:
    detector: dedode
    matcher: roma

task:
    name: basalt  # samples basalt
    consider_samples: False # True False
    
    # basalt related
    
    limit_count: 0
    
    dataset: monado_slam  # euroc monado_slam

    track: MOO04_hand_shooter_hard
    tracks:
        - MGO07_mapping_easy
        - MOO07_mapping_easy
        - MOO09_short_1_updown
        - MOO10_short_2_panorama
        - MOO11_short_3_backandforth
        - MGO08_mapping_hard  
        # - MGO13_sudden_movements # must runn 
        # - MGO14_flickering_light # must runn
        # - MOO04_hand_shooter_hard # must run 

    cam: cam0
    cams:
        - cam0
        - cam1

samples:
    samples:
        reference: toronto_A.jpg
        target: toronto_B.jpg
    basalt:
        reference: 8657652230990
        target: 8657685519990

paths:
    roots:
        ws: /home/stud/ath/ath_ws # /home/stud/ath/ath_ws  D:/thesis_code
        mav: ${paths.roots.ws}/datasets/${task.dataset}/${task.track}/mav0
        project: ${paths.roots.ws}/keypoint_dataset_pipeline
        output: ${paths.roots.project}/output

    samples:
        images: ${paths.roots.project}/data/samples/images
        output: ${paths.roots.output}/samples
    basalt:
        images_csv: ${paths.roots.mav}/${task.cam}/data.csv
        imu_csv: ${paths.roots.mav}/imu0/data.csv
        images: ${paths.roots.mav}/${task.cam}/data
        output: ${paths.roots.output}/${task.name}/${task.dataset}/${task.track}
        train_data: ${paths.roots.output}/train_6

image:
    # [width, height]
    original_image_shape: [640, 480]  # [640, 480]
    crop_image_shape: [ 630, 476 ] # [504, 504] [630, 476]

dedode:
    batch_size: 6
    image_keypoints_count: 400

    filter:
        # weighted sampling
        images_sample_count: 200

roma:
    filter:
        # keep matches over the absolute confidence threshold
        confidence_threshold: 0.6
