components:
    detector: dedode
    matcher: roma

task:
    name: samples  # samples basalt
    consider_samples: True # True False
    limit_count: 0
    track: V1_01_easy
    cam: cam0 # cam0 cam1

samples:
    samples:
        reference: sacre_coeur_A.jpg
        target: sacre_coeur_B.jpg
    basalt:
        reference: 1403636661163555584
        target: 1403636661513555456

paths:
    roots:
        ws: /home/stud/ath/ath_ws
        mav: ${paths.roots.ws}/datasets/euroc/${task.track}/mav0
        project: ${paths.roots.ws}/keypoint_dataset_pipeline
        outputs: ${paths.roots.project}/outputs/${task.name}/${task.track}/${task.cam}

    samples:
        images_dir: ${paths.project_root}/data/samples/images
        tensors_dir: ${paths.project_root}/data/samples/tensors
    basalt:
        csv: ${paths.roots.mav}/${task.cam}/data.csv
        images_dir: ${paths.roots.mav}/${task.cam}/data
        tensors_dir: ${paths.roots.project}/tensors/${task.name}/${task.track}/${task.cam}
        zip_dir: ${paths.roots.project}/zips/${task.name}/${task.track}/${task.cam}

image:
    image_shape: [504, 504]
    patch_shape: [84, 84]  # [42, 42]  [84, 84]

dedode:
    batch_size: 6
    image_keypoints_count: 300
    patch_keypoints_count: 2

    filter:
        # weighted sampling
        images_sample_count: 100
        patches_sample_count: 10

roma:
    filter:
        # keep matches over the absolute confidence threshold
        confidence_threshold: 0.6
