components:
    detector: dedode
    matcher: roma

task: samples  # samples basalt

samples:
    reference: sacre_coeur_A.jpg
    target: sacre_coeur_B.jpg

paths:
    samples:
        images_dir: /home/stud/ath/ath_ws/keypoint_dataset_pipeline/data/samples/images
        tensors_dir: /home/stud/ath/ath_ws/keypoint_dataset_pipeline/data/samples/tensors
    basalt:
        images_dir: /home/stud/ath/ath_ws/keypoint_dataset_pipeline/data/euroc/images
        tensors_dir: /home/stud/ath/ath_ws/keypoint_dataset_pipeline/data/euroc/tensors
        csv: /home/stud/ath/ath_ws/keypoint_dataset_pipeline/data/euroc/EuRoC_V1_01_easy_filenames.csv

image:
    image_shape: [512, 512] # [448, 448]
    patch_shape: [64, 64]

dedode:
    image_keypoints_count: 5_000
    patch_keypoints_count: 5_00

    filter:
        image_relative_confidence_threshold: 0.4
        patches_relative_confidence_threshold: 0.2

        choosing_strategy: weighted_sampling  # sorting weighted_sampling
        max_count: 1_000

roma:
    filter:
        confidence_threshold: 0.5  # absolute confidence
