components:
    detector: dedode
    matcher: roma

task: basalt  # samples basalt basalt_samples

samples:
    reference: 1403715273612143104.png  # sacre_coeur_A.jpg
    target: 1403715275012143104.png  # sacre_coeur_B.jpg

paths:
    samples:
        images_dir: /home/stud/ath/ath_ws/keypoint_dataset_pipeline/data/samples/images
        tensors_dir: /home/stud/ath/ath_ws/keypoint_dataset_pipeline/data/samples/tensors
    basalt_samples:
        images_dir: /home/stud/ath/ath_ws/datasets/euroc/V1_01_easy/mav0/cam0/data
        tensors_dir: /home/stud/ath/ath_ws/keypoint_dataset_pipeline/data/euroc/tensors
    basalt:
        images_dir: /home/stud/ath/ath_ws/datasets/euroc/V1_01_easy/mav0/cam0/data
        tensors_dir: /home/stud/ath/ath_ws/keypoint_dataset_pipeline/data/euroc/tensors
        csv: /home/stud/ath/ath_ws/keypoint_dataset_pipeline/data/euroc/EuRoC_V1_01_easy_filenames.csv

image:
    image_shape: [512, 512] # [448, 448]
    patch_shape: [64, 64]

dedode:
    image_keypoints_count: 1_000
    patch_keypoints_count: 200

    filter:
        sample_count: 300

roma:
    filter:
        # keep matches over the absolute confidence threshold
        confidence_threshold: 0.5
